---

- hosts: all
  gather_facts: no
  become: true
  tasks:

    - name: update repository index
      yum:
        update_cache: yes
        state: latest

    - name: install python3
      yum:
        name: python3

    - name: add phpd for apache
      yum:
        name: httpd
        state: latest
